package emch.modelo.entidades;
// Generated 30-abr-2013 18:02:46 by Hibernate Tools 3.2.1.GA



/**
 * TAccesoe generated by hbm2java
 */
public class TAccesoe  implements java.io.Serializable {


     private int idAe;
     private TGrupoacceso TGrupoacceso;
     private TEmpresa TEmpresa;
     private TPerfil TPerfil;

    public TAccesoe() {
    }

    public TAccesoe(int idAe, TGrupoacceso TGrupoacceso, TEmpresa TEmpresa, TPerfil TPerfil) {
       this.idAe = idAe;
       this.TGrupoacceso = TGrupoacceso;
       this.TEmpresa = TEmpresa;
       this.TPerfil = TPerfil;
    }
   
    public int getIdAe() {
        return this.idAe;
    }
    
    public void setIdAe(int idAe) {
        this.idAe = idAe;
    }
    public TGrupoacceso getTGrupoacceso() {
        return this.TGrupoacceso;
    }
    
    public void setTGrupoacceso(TGrupoacceso TGrupoacceso) {
        this.TGrupoacceso = TGrupoacceso;
    }
    public TEmpresa getTEmpresa() {
        return this.TEmpresa;
    }
    
    public void setTEmpresa(TEmpresa TEmpresa) {
        this.TEmpresa = TEmpresa;
    }
    public TPerfil getTPerfil() {
        return this.TPerfil;
    }
    
    public void setTPerfil(TPerfil TPerfil) {
        this.TPerfil = TPerfil;
    }




}


