package emch.modelo.entidades;
// Generated 30-abr-2013 18:02:46 by Hibernate Tools 3.2.1.GA



/**
 * TAsistenciaxtrabajador generated by hbm2java
 */
public class TAsistenciaxtrabajador  implements java.io.Serializable {


     private TAsistenciaxtrabajadorId id;
     private TTrabajador TTrabajador;
     private TAsistencia TAsistencia;
     private boolean asiste;
     private boolean tardanza;
     private boolean fustifica;

    public TAsistenciaxtrabajador() {
    }

    public TAsistenciaxtrabajador(TAsistenciaxtrabajadorId id, TTrabajador TTrabajador, TAsistencia TAsistencia, boolean asiste, boolean tardanza, boolean fustifica) {
       this.id = id;
       this.TTrabajador = TTrabajador;
       this.TAsistencia = TAsistencia;
       this.asiste = asiste;
       this.tardanza = tardanza;
       this.fustifica = fustifica;
    }
   
    public TAsistenciaxtrabajadorId getId() {
        return this.id;
    }
    
    public void setId(TAsistenciaxtrabajadorId id) {
        this.id = id;
    }
    public TTrabajador getTTrabajador() {
        return this.TTrabajador;
    }
    
    public void setTTrabajador(TTrabajador TTrabajador) {
        this.TTrabajador = TTrabajador;
    }
    public TAsistencia getTAsistencia() {
        return this.TAsistencia;
    }
    
    public void setTAsistencia(TAsistencia TAsistencia) {
        this.TAsistencia = TAsistencia;
    }
    public boolean isAsiste() {
        return this.asiste;
    }
    
    public void setAsiste(boolean asiste) {
        this.asiste = asiste;
    }
    public boolean isTardanza() {
        return this.tardanza;
    }
    
    public void setTardanza(boolean tardanza) {
        this.tardanza = tardanza;
    }
    public boolean isFustifica() {
        return this.fustifica;
    }
    
    public void setFustifica(boolean fustifica) {
        this.fustifica = fustifica;
    }




}


