package emch.modelo.entidades;
// Generated 29-may-2013 1:03:45 by Hibernate Tools 3.2.1.GA



/**
 * TAsignarruta generated by hbm2java
 */
public class TAsignarruta  implements java.io.Serializable {


     private String cdRuta;
     private TDespachodet TDespachodet;
     private Double center;
     private Double latitud;
     private Double longitud;
     private int nroV;

    public TAsignarruta() {
    }

	
    public TAsignarruta(String cdRuta, TDespachodet TDespachodet, int nroV) {
        this.cdRuta = cdRuta;
        this.TDespachodet = TDespachodet;
        this.nroV = nroV;
    }
    public TAsignarruta(String cdRuta, TDespachodet TDespachodet, Double center, Double latitud, Double longitud, int nroV) {
       this.cdRuta = cdRuta;
       this.TDespachodet = TDespachodet;
       this.center = center;
       this.latitud = latitud;
       this.longitud = longitud;
       this.nroV = nroV;
    }
   
    public String getCdRuta() {
        return this.cdRuta;
    }
    
    public void setCdRuta(String cdRuta) {
        this.cdRuta = cdRuta;
    }
    public TDespachodet getTDespachodet() {
        return this.TDespachodet;
    }
    
    public void setTDespachodet(TDespachodet TDespachodet) {
        this.TDespachodet = TDespachodet;
    }
    public Double getCenter() {
        return this.center;
    }
    
    public void setCenter(Double center) {
        this.center = center;
    }
    public Double getLatitud() {
        return this.latitud;
    }
    
    public void setLatitud(Double latitud) {
        this.latitud = latitud;
    }
    public Double getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(Double longitud) {
        this.longitud = longitud;
    }
    public int getNroV() {
        return this.nroV;
    }
    
    public void setNroV(int nroV) {
        this.nroV = nroV;
    }




}


