package emch.modelo.entidades;
// Generated 01/11/2013 08:35:39 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * TCamion generated by hbm2java
 */
public class TCamion  implements java.io.Serializable {


     private String cdCamion;
     private int unidad;
     private String placa;
     private String marca;
     private String clase;
     private String anioFab;
     private String anioAdq;
     private String nroMotor;
     private BigDecimal pesoBruto;
     private String tipoCombustible;
     private BigDecimal kilometraje;
     private byte[] imagen;
     private boolean estado;
     private Set<TTrabajadorxcamion> TTrabajadorxcamions = new HashSet<TTrabajadorxcamion>(0);

    public TCamion() {
    }

	
    public TCamion(String cdCamion, int unidad, String placa, String marca, String clase, String anioFab, String anioAdq, String nroMotor, BigDecimal pesoBruto, String tipoCombustible, BigDecimal kilometraje, boolean estado) {
        this.cdCamion = cdCamion;
        this.unidad = unidad;
        this.placa = placa;
        this.marca = marca;
        this.clase = clase;
        this.anioFab = anioFab;
        this.anioAdq = anioAdq;
        this.nroMotor = nroMotor;
        this.pesoBruto = pesoBruto;
        this.tipoCombustible = tipoCombustible;
        this.kilometraje = kilometraje;
        this.estado = estado;
    }
    public TCamion(String cdCamion, int unidad, String placa, String marca, String clase, String anioFab, String anioAdq, String nroMotor, BigDecimal pesoBruto, String tipoCombustible, BigDecimal kilometraje, byte[] imagen, boolean estado, Set<TTrabajadorxcamion> TTrabajadorxcamions) {
       this.cdCamion = cdCamion;
       this.unidad = unidad;
       this.placa = placa;
       this.marca = marca;
       this.clase = clase;
       this.anioFab = anioFab;
       this.anioAdq = anioAdq;
       this.nroMotor = nroMotor;
       this.pesoBruto = pesoBruto;
       this.tipoCombustible = tipoCombustible;
       this.kilometraje = kilometraje;
       this.imagen = imagen;
       this.estado = estado;
       this.TTrabajadorxcamions = TTrabajadorxcamions;
    }
   
    public String getCdCamion() {
        return this.cdCamion;
    }
    
    public void setCdCamion(String cdCamion) {
        this.cdCamion = cdCamion;
    }
    public int getUnidad() {
        return this.unidad;
    }
    
    public void setUnidad(int unidad) {
        this.unidad = unidad;
    }
    public String getPlaca() {
        return this.placa;
    }
    
    public void setPlaca(String placa) {
        this.placa = placa;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getClase() {
        return this.clase;
    }
    
    public void setClase(String clase) {
        this.clase = clase;
    }
    public String getAnioFab() {
        return this.anioFab;
    }
    
    public void setAnioFab(String anioFab) {
        this.anioFab = anioFab;
    }
    public String getAnioAdq() {
        return this.anioAdq;
    }
    
    public void setAnioAdq(String anioAdq) {
        this.anioAdq = anioAdq;
    }
    public String getNroMotor() {
        return this.nroMotor;
    }
    
    public void setNroMotor(String nroMotor) {
        this.nroMotor = nroMotor;
    }
    public BigDecimal getPesoBruto() {
        return this.pesoBruto;
    }
    
    public void setPesoBruto(BigDecimal pesoBruto) {
        this.pesoBruto = pesoBruto;
    }
    public String getTipoCombustible() {
        return this.tipoCombustible;
    }
    
    public void setTipoCombustible(String tipoCombustible) {
        this.tipoCombustible = tipoCombustible;
    }
    public BigDecimal getKilometraje() {
        return this.kilometraje;
    }
    
    public void setKilometraje(BigDecimal kilometraje) {
        this.kilometraje = kilometraje;
    }
    public byte[] getImagen() {
        return this.imagen;
    }
    
    public void setImagen(byte[] imagen) {
        this.imagen = imagen;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public Set<TTrabajadorxcamion> getTTrabajadorxcamions() {
        return this.TTrabajadorxcamions;
    }
    
    public void setTTrabajadorxcamions(Set<TTrabajadorxcamion> TTrabajadorxcamions) {
        this.TTrabajadorxcamions = TTrabajadorxcamions;
    }




}


