package emch.modelo.entidades;
// Generated 30-abr-2013 18:02:46 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TDespacho generated by hbm2java
 */
public class TDespacho  implements java.io.Serializable {


     private TDespachoId id;
     private TTurno TTurno;
     private TEmpresa TEmpresa;
     private TUbigeo TUbigeo;
     private Date fechaEmi;
     private String nroDespacho;
     private String zona;
     private BigDecimal dineroEnviado;
     private BigDecimal totalDineroUso;
     private BigDecimal totalDineroSinUso;
     private String usuCrea;
     private Date fechaReg;
     private String usuModf;
     private Date fechaModf;
     private Character evaluacion;
     private String obs;
     private Set<TDespachodet> TDespachodets = new HashSet<TDespachodet>(0);
     private Set<TControlviaje> TControlviajes = new HashSet<TControlviaje>(0);

    public TDespacho() {
    }

	
    public TDespacho(TDespachoId id, TTurno TTurno, TEmpresa TEmpresa, TUbigeo TUbigeo, Date fechaEmi, String nroDespacho, String zona, BigDecimal dineroEnviado, String usuCrea, Date fechaReg) {
        this.id = id;
        this.TTurno = TTurno;
        this.TEmpresa = TEmpresa;
        this.TUbigeo = TUbigeo;
        this.fechaEmi = fechaEmi;
        this.nroDespacho = nroDespacho;
        this.zona = zona;
        this.dineroEnviado = dineroEnviado;
        this.usuCrea = usuCrea;
        this.fechaReg = fechaReg;
    }
    public TDespacho(TDespachoId id, TTurno TTurno, TEmpresa TEmpresa, TUbigeo TUbigeo, Date fechaEmi, String nroDespacho, String zona, BigDecimal dineroEnviado, BigDecimal totalDineroUso, BigDecimal totalDineroSinUso, String usuCrea, Date fechaReg, String usuModf, Date fechaModf, Character evaluacion, String obs, Set<TDespachodet> TDespachodets, Set<TControlviaje> TControlviajes) {
       this.id = id;
       this.TTurno = TTurno;
       this.TEmpresa = TEmpresa;
       this.TUbigeo = TUbigeo;
       this.fechaEmi = fechaEmi;
       this.nroDespacho = nroDespacho;
       this.zona = zona;
       this.dineroEnviado = dineroEnviado;
       this.totalDineroUso = totalDineroUso;
       this.totalDineroSinUso = totalDineroSinUso;
       this.usuCrea = usuCrea;
       this.fechaReg = fechaReg;
       this.usuModf = usuModf;
       this.fechaModf = fechaModf;
       this.evaluacion = evaluacion;
       this.obs = obs;
       this.TDespachodets = TDespachodets;
       this.TControlviajes = TControlviajes;
    }
   
    public TDespachoId getId() {
        return this.id;
    }
    
    public void setId(TDespachoId id) {
        this.id = id;
    }
    public TTurno getTTurno() {
        return this.TTurno;
    }
    
    public void setTTurno(TTurno TTurno) {
        this.TTurno = TTurno;
    }
    public TEmpresa getTEmpresa() {
        return this.TEmpresa;
    }
    
    public void setTEmpresa(TEmpresa TEmpresa) {
        this.TEmpresa = TEmpresa;
    }
    public TUbigeo getTUbigeo() {
        return this.TUbigeo;
    }
    
    public void setTUbigeo(TUbigeo TUbigeo) {
        this.TUbigeo = TUbigeo;
    }
    public Date getFechaEmi() {
        return this.fechaEmi;
    }
    
    public void setFechaEmi(Date fechaEmi) {
        this.fechaEmi = fechaEmi;
    }
    public String getNroDespacho() {
        return this.nroDespacho;
    }
    
    public void setNroDespacho(String nroDespacho) {
        this.nroDespacho = nroDespacho;
    }
    public String getZona() {
        return this.zona;
    }
    
    public void setZona(String zona) {
        this.zona = zona;
    }
    public BigDecimal getDineroEnviado() {
        return this.dineroEnviado;
    }
    
    public void setDineroEnviado(BigDecimal dineroEnviado) {
        this.dineroEnviado = dineroEnviado;
    }
    public BigDecimal getTotalDineroUso() {
        return this.totalDineroUso;
    }
    
    public void setTotalDineroUso(BigDecimal totalDineroUso) {
        this.totalDineroUso = totalDineroUso;
    }
    public BigDecimal getTotalDineroSinUso() {
        return this.totalDineroSinUso;
    }
    
    public void setTotalDineroSinUso(BigDecimal totalDineroSinUso) {
        this.totalDineroSinUso = totalDineroSinUso;
    }
    public String getUsuCrea() {
        return this.usuCrea;
    }
    
    public void setUsuCrea(String usuCrea) {
        this.usuCrea = usuCrea;
    }
    public Date getFechaReg() {
        return this.fechaReg;
    }
    
    public void setFechaReg(Date fechaReg) {
        this.fechaReg = fechaReg;
    }
    public String getUsuModf() {
        return this.usuModf;
    }
    
    public void setUsuModf(String usuModf) {
        this.usuModf = usuModf;
    }
    public Date getFechaModf() {
        return this.fechaModf;
    }
    
    public void setFechaModf(Date fechaModf) {
        this.fechaModf = fechaModf;
    }
    public Character getEvaluacion() {
        return this.evaluacion;
    }
    
    public void setEvaluacion(Character evaluacion) {
        this.evaluacion = evaluacion;
    }
    public String getObs() {
        return this.obs;
    }
    
    public void setObs(String obs) {
        this.obs = obs;
    }
    public Set<TDespachodet> getTDespachodets() {
        return this.TDespachodets;
    }
    
    public void setTDespachodets(Set<TDespachodet> TDespachodets) {
        this.TDespachodets = TDespachodets;
    }
    public Set<TControlviaje> getTControlviajes() {
        return this.TControlviajes;
    }
    
    public void setTControlviajes(Set<TControlviaje> TControlviajes) {
        this.TControlviajes = TControlviajes;
    }




}


