package emch.modelo.entidades;
// Generated 31-may-2013 22:17:08 by Hibernate Tools 3.2.1.GA



/**
 * TImgspesajeId generated by hbm2java
 */
public class TImgspesajeId  implements java.io.Serializable {


     private String cdImg;
     private String cdPesaje;

    public TImgspesajeId() {
    }

    public TImgspesajeId(String cdImg, String cdPesaje) {
       this.cdImg = cdImg;
       this.cdPesaje = cdPesaje;
    }
   
    public String getCdImg() {
        return this.cdImg;
    }
    
    public void setCdImg(String cdImg) {
        this.cdImg = cdImg;
    }
    public String getCdPesaje() {
        return this.cdPesaje;
    }
    
    public void setCdPesaje(String cdPesaje) {
        this.cdPesaje = cdPesaje;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TImgspesajeId) ) return false;
		 TImgspesajeId castOther = ( TImgspesajeId ) other; 
         
		 return ( (this.getCdImg()==castOther.getCdImg()) || ( this.getCdImg()!=null && castOther.getCdImg()!=null && this.getCdImg().equals(castOther.getCdImg()) ) )
 && ( (this.getCdPesaje()==castOther.getCdPesaje()) || ( this.getCdPesaje()!=null && castOther.getCdPesaje()!=null && this.getCdPesaje().equals(castOther.getCdPesaje()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCdImg() == null ? 0 : this.getCdImg().hashCode() );
         result = 37 * result + ( getCdPesaje() == null ? 0 : this.getCdPesaje().hashCode() );
         return result;
   }   


}


