package emch.modelo.entidades;
// Generated 30-abr-2013 18:02:46 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * TIncidencia generated by hbm2java
 */
public class TIncidencia  implements java.io.Serializable {


     private TIncidenciaId id;
     private TControlviaje TControlviaje;
     private Date fechaInc;
     private String zona;
     private String problema;
     private String horaProb;
     private String observaciones;
     private String soluc;

    public TIncidencia() {
    }

	
    public TIncidencia(TIncidenciaId id, TControlviaje TControlviaje, Date fechaInc, String zona, String problema, String horaProb) {
        this.id = id;
        this.TControlviaje = TControlviaje;
        this.fechaInc = fechaInc;
        this.zona = zona;
        this.problema = problema;
        this.horaProb = horaProb;
    }
    public TIncidencia(TIncidenciaId id, TControlviaje TControlviaje, Date fechaInc, String zona, String problema, String horaProb, String observaciones, String soluc) {
       this.id = id;
       this.TControlviaje = TControlviaje;
       this.fechaInc = fechaInc;
       this.zona = zona;
       this.problema = problema;
       this.horaProb = horaProb;
       this.observaciones = observaciones;
       this.soluc = soluc;
    }
   
    public TIncidenciaId getId() {
        return this.id;
    }
    
    public void setId(TIncidenciaId id) {
        this.id = id;
    }
    public TControlviaje getTControlviaje() {
        return this.TControlviaje;
    }
    
    public void setTControlviaje(TControlviaje TControlviaje) {
        this.TControlviaje = TControlviaje;
    }
    public Date getFechaInc() {
        return this.fechaInc;
    }
    
    public void setFechaInc(Date fechaInc) {
        this.fechaInc = fechaInc;
    }
    public String getZona() {
        return this.zona;
    }
    
    public void setZona(String zona) {
        this.zona = zona;
    }
    public String getProblema() {
        return this.problema;
    }
    
    public void setProblema(String problema) {
        this.problema = problema;
    }
    public String getHoraProb() {
        return this.horaProb;
    }
    
    public void setHoraProb(String horaProb) {
        this.horaProb = horaProb;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public String getSoluc() {
        return this.soluc;
    }
    
    public void setSoluc(String soluc) {
        this.soluc = soluc;
    }




}


