package emch.modelo.entidades;
// Generated 30-abr-2013 18:02:46 by Hibernate Tools 3.2.1.GA



/**
 * TIncidenciaId generated by hbm2java
 */
public class TIncidenciaId  implements java.io.Serializable {


     private String cdInc;
     private String cdControlViaje;

    public TIncidenciaId() {
    }

    public TIncidenciaId(String cdInc, String cdControlViaje) {
       this.cdInc = cdInc;
       this.cdControlViaje = cdControlViaje;
    }
   
    public String getCdInc() {
        return this.cdInc;
    }
    
    public void setCdInc(String cdInc) {
        this.cdInc = cdInc;
    }
    public String getCdControlViaje() {
        return this.cdControlViaje;
    }
    
    public void setCdControlViaje(String cdControlViaje) {
        this.cdControlViaje = cdControlViaje;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TIncidenciaId) ) return false;
		 TIncidenciaId castOther = ( TIncidenciaId ) other; 
         
		 return ( (this.getCdInc()==castOther.getCdInc()) || ( this.getCdInc()!=null && castOther.getCdInc()!=null && this.getCdInc().equals(castOther.getCdInc()) ) )
 && ( (this.getCdControlViaje()==castOther.getCdControlViaje()) || ( this.getCdControlViaje()!=null && castOther.getCdControlViaje()!=null && this.getCdControlViaje().equals(castOther.getCdControlViaje()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCdInc() == null ? 0 : this.getCdInc().hashCode() );
         result = 37 * result + ( getCdControlViaje() == null ? 0 : this.getCdControlViaje().hashCode() );
         return result;
   }   


}


