package emch.modelo.entidades;
// Generated 13-jun-2013 0:55:31 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TSoat generated by hbm2java
 */
public class TSoat  implements java.io.Serializable {


     private int idSoat;
     private String nombreSoat;
     private String telf;
     private Set<TSoatxcamion> TSoatxcamions = new HashSet<TSoatxcamion>(0);

    public TSoat() {
    }

	
    public TSoat(int idSoat, String nombreSoat) {
        this.idSoat = idSoat;
        this.nombreSoat = nombreSoat;
    }
    public TSoat(int idSoat, String nombreSoat, String telf, Set<TSoatxcamion> TSoatxcamions) {
       this.idSoat = idSoat;
       this.nombreSoat = nombreSoat;
       this.telf = telf;
       this.TSoatxcamions = TSoatxcamions;
    }
   
    public int getIdSoat() {
        return this.idSoat;
    }
    
    public void setIdSoat(int idSoat) {
        this.idSoat = idSoat;
    }
    public String getNombreSoat() {
        return this.nombreSoat;
    }
    
    public void setNombreSoat(String nombreSoat) {
        this.nombreSoat = nombreSoat;
    }
    public String getTelf() {
        return this.telf;
    }
    
    public void setTelf(String telf) {
        this.telf = telf;
    }
    public Set<TSoatxcamion> getTSoatxcamions() {
        return this.TSoatxcamions;
    }
    
    public void setTSoatxcamions(Set<TSoatxcamion> TSoatxcamions) {
        this.TSoatxcamions = TSoatxcamions;
    }




}


