package emch.modelo.entidades;
// Generated 01/11/2013 08:35:39 PM by Hibernate Tools 3.2.1.GA



/**
 * TAsistenciaxtrabajadorId generated by hbm2java
 */
public class TAsistenciaxtrabajadorId  implements java.io.Serializable {


     private String cdTrabajador;
     private String cdAsistencia;

    public TAsistenciaxtrabajadorId() {
    }

    public TAsistenciaxtrabajadorId(String cdTrabajador, String cdAsistencia) {
       this.cdTrabajador = cdTrabajador;
       this.cdAsistencia = cdAsistencia;
    }
   
    public String getCdTrabajador() {
        return this.cdTrabajador;
    }
    
    public void setCdTrabajador(String cdTrabajador) {
        this.cdTrabajador = cdTrabajador;
    }
    public String getCdAsistencia() {
        return this.cdAsistencia;
    }
    
    public void setCdAsistencia(String cdAsistencia) {
        this.cdAsistencia = cdAsistencia;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TAsistenciaxtrabajadorId) ) return false;
		 TAsistenciaxtrabajadorId castOther = ( TAsistenciaxtrabajadorId ) other; 
         
		 return ( (this.getCdTrabajador()==castOther.getCdTrabajador()) || ( this.getCdTrabajador()!=null && castOther.getCdTrabajador()!=null && this.getCdTrabajador().equals(castOther.getCdTrabajador()) ) )
 && ( (this.getCdAsistencia()==castOther.getCdAsistencia()) || ( this.getCdAsistencia()!=null && castOther.getCdAsistencia()!=null && this.getCdAsistencia().equals(castOther.getCdAsistencia()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCdTrabajador() == null ? 0 : this.getCdTrabajador().hashCode() );
         result = 37 * result + ( getCdAsistencia() == null ? 0 : this.getCdAsistencia().hashCode() );
         return result;
   }   


}


