package emch.modelo.entidades;
// Generated May 23, 2013 7:29:14 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * TComprobantedet generated by hbm2java
 */
public class TComprobantedet  implements java.io.Serializable {


     private String item;
     private TComprobante TComprobante;
     private TServicio TServicio;
     private BigDecimal precioUnit;
     private BigDecimal igv;
     private BigDecimal total;

    public TComprobantedet() {
    }

    public TComprobantedet(String item, TComprobante TComprobante, TServicio TServicio, BigDecimal precioUnit, BigDecimal igv, BigDecimal total) {
       this.item = item;
       this.TComprobante = TComprobante;
       this.TServicio = TServicio;
       this.precioUnit = precioUnit;
       this.igv = igv;
       this.total = total;
    }
   
    public String getItem() {
        return this.item;
    }
    
    public void setItem(String item) {
        this.item = item;
    }
    public TComprobante getTComprobante() {
        return this.TComprobante;
    }
    
    public void setTComprobante(TComprobante TComprobante) {
        this.TComprobante = TComprobante;
    }
    public TServicio getTServicio() {
        return this.TServicio;
    }
    
    public void setTServicio(TServicio TServicio) {
        this.TServicio = TServicio;
    }
    public BigDecimal getPrecioUnit() {
        return this.precioUnit;
    }
    
    public void setPrecioUnit(BigDecimal precioUnit) {
        this.precioUnit = precioUnit;
    }
    public BigDecimal getIgv() {
        return this.igv;
    }
    
    public void setIgv(BigDecimal igv) {
        this.igv = igv;
    }
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }




}


