package emch.modelo.entidades;
// Generated 01/11/2013 08:35:39 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * TComprobantedet generated by hbm2java
 */
public class TComprobantedet  implements java.io.Serializable {


     private String item;
     private TComprobante TComprobante;
     private TServicio TServicio;
     private BigDecimal precio;
     private BigDecimal cantTn;
     private BigDecimal total;

    public TComprobantedet() {
    }

    public TComprobantedet(String item, TComprobante TComprobante, TServicio TServicio, BigDecimal precio, BigDecimal cantTn, BigDecimal total) {
       this.item = item;
       this.TComprobante = TComprobante;
       this.TServicio = TServicio;
       this.precio = precio;
       this.cantTn = cantTn;
       this.total = total;
    }
   
    public String getItem() {
        return this.item;
    }
    
    public void setItem(String item) {
        this.item = item;
    }
    public TComprobante getTComprobante() {
        return this.TComprobante;
    }
    
    public void setTComprobante(TComprobante TComprobante) {
        this.TComprobante = TComprobante;
    }
    public TServicio getTServicio() {
        return this.TServicio;
    }
    
    public void setTServicio(TServicio TServicio) {
        this.TServicio = TServicio;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    public BigDecimal getCantTn() {
        return this.cantTn;
    }
    
    public void setCantTn(BigDecimal cantTn) {
        this.cantTn = cantTn;
    }
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }




}


