package emch.modelo.entidades;
// Generated 30-abr-2013 18:02:46 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TControlviaje generated by hbm2java
 */
public class TControlviaje  implements java.io.Serializable {


     private String cdControlViaje;
     private TDespacho TDespacho;
     private Date fechaEmi;
     private String horaEstimada;
     private String horaReal;
     private Integer nroViaje;
     private String obs;
     private Set<TIncidencia> TIncidencias = new HashSet<TIncidencia>(0);

    public TControlviaje() {
    }

	
    public TControlviaje(String cdControlViaje, TDespacho TDespacho, Date fechaEmi, String horaEstimada, String horaReal) {
        this.cdControlViaje = cdControlViaje;
        this.TDespacho = TDespacho;
        this.fechaEmi = fechaEmi;
        this.horaEstimada = horaEstimada;
        this.horaReal = horaReal;
    }
    public TControlviaje(String cdControlViaje, TDespacho TDespacho, Date fechaEmi, String horaEstimada, String horaReal, Integer nroViaje, String obs, Set<TIncidencia> TIncidencias) {
       this.cdControlViaje = cdControlViaje;
       this.TDespacho = TDespacho;
       this.fechaEmi = fechaEmi;
       this.horaEstimada = horaEstimada;
       this.horaReal = horaReal;
       this.nroViaje = nroViaje;
       this.obs = obs;
       this.TIncidencias = TIncidencias;
    }
   
    public String getCdControlViaje() {
        return this.cdControlViaje;
    }
    
    public void setCdControlViaje(String cdControlViaje) {
        this.cdControlViaje = cdControlViaje;
    }
    public TDespacho getTDespacho() {
        return this.TDespacho;
    }
    
    public void setTDespacho(TDespacho TDespacho) {
        this.TDespacho = TDespacho;
    }
    public Date getFechaEmi() {
        return this.fechaEmi;
    }
    
    public void setFechaEmi(Date fechaEmi) {
        this.fechaEmi = fechaEmi;
    }
    public String getHoraEstimada() {
        return this.horaEstimada;
    }
    
    public void setHoraEstimada(String horaEstimada) {
        this.horaEstimada = horaEstimada;
    }
    public String getHoraReal() {
        return this.horaReal;
    }
    
    public void setHoraReal(String horaReal) {
        this.horaReal = horaReal;
    }
    public Integer getNroViaje() {
        return this.nroViaje;
    }
    
    public void setNroViaje(Integer nroViaje) {
        this.nroViaje = nroViaje;
    }
    public String getObs() {
        return this.obs;
    }
    
    public void setObs(String obs) {
        this.obs = obs;
    }
    public Set<TIncidencia> getTIncidencias() {
        return this.TIncidencias;
    }
    
    public void setTIncidencias(Set<TIncidencia> TIncidencias) {
        this.TIncidencias = TIncidencias;
    }




}


