package emch.modelo.entidades;
// Generated 30-abr-2013 18:02:46 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TDespachodet generated by hbm2java
 */
public class TDespachodet  implements java.io.Serializable {


     private TDespachodetId id;
     private TDespacho TDespacho;
     private TTrabajadorxcamion TTrabajadorxcamion;
     private String cantViaje;
     private Set<TAsignarruta> TAsignarrutas = new HashSet<TAsignarruta>(0);

    public TDespachodet() {
    }

	
    public TDespachodet(TDespachodetId id, TDespacho TDespacho, TTrabajadorxcamion TTrabajadorxcamion, String cantViaje) {
        this.id = id;
        this.TDespacho = TDespacho;
        this.TTrabajadorxcamion = TTrabajadorxcamion;
        this.cantViaje = cantViaje;
    }
    public TDespachodet(TDespachodetId id, TDespacho TDespacho, TTrabajadorxcamion TTrabajadorxcamion, String cantViaje, Set<TAsignarruta> TAsignarrutas) {
       this.id = id;
       this.TDespacho = TDespacho;
       this.TTrabajadorxcamion = TTrabajadorxcamion;
       this.cantViaje = cantViaje;
       this.TAsignarrutas = TAsignarrutas;
    }
   
    public TDespachodetId getId() {
        return this.id;
    }
    
    public void setId(TDespachodetId id) {
        this.id = id;
    }
    public TDespacho getTDespacho() {
        return this.TDespacho;
    }
    
    public void setTDespacho(TDespacho TDespacho) {
        this.TDespacho = TDespacho;
    }
    public TTrabajadorxcamion getTTrabajadorxcamion() {
        return this.TTrabajadorxcamion;
    }
    
    public void setTTrabajadorxcamion(TTrabajadorxcamion TTrabajadorxcamion) {
        this.TTrabajadorxcamion = TTrabajadorxcamion;
    }
    public String getCantViaje() {
        return this.cantViaje;
    }
    
    public void setCantViaje(String cantViaje) {
        this.cantViaje = cantViaje;
    }
    public Set<TAsignarruta> getTAsignarrutas() {
        return this.TAsignarrutas;
    }
    
    public void setTAsignarrutas(Set<TAsignarruta> TAsignarrutas) {
        this.TAsignarrutas = TAsignarrutas;
    }




}


