package emch.modelo.entidades;
// Generated 30-abr-2013 18:02:46 by Hibernate Tools 3.2.1.GA



/**
 * TDespachodetId generated by hbm2java
 */
public class TDespachodetId  implements java.io.Serializable {


     private int nro;
     private String rucE;
     private String cdDespacho;

    public TDespachodetId() {
    }

    public TDespachodetId(int nro, String rucE, String cdDespacho) {
       this.nro = nro;
       this.rucE = rucE;
       this.cdDespacho = cdDespacho;
    }
   
    public int getNro() {
        return this.nro;
    }
    
    public void setNro(int nro) {
        this.nro = nro;
    }
    public String getRucE() {
        return this.rucE;
    }
    
    public void setRucE(String rucE) {
        this.rucE = rucE;
    }
    public String getCdDespacho() {
        return this.cdDespacho;
    }
    
    public void setCdDespacho(String cdDespacho) {
        this.cdDespacho = cdDespacho;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TDespachodetId) ) return false;
		 TDespachodetId castOther = ( TDespachodetId ) other; 
         
		 return (this.getNro()==castOther.getNro())
 && ( (this.getRucE()==castOther.getRucE()) || ( this.getRucE()!=null && castOther.getRucE()!=null && this.getRucE().equals(castOther.getRucE()) ) )
 && ( (this.getCdDespacho()==castOther.getCdDespacho()) || ( this.getCdDespacho()!=null && castOther.getCdDespacho()!=null && this.getCdDespacho().equals(castOther.getCdDespacho()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getNro();
         result = 37 * result + ( getRucE() == null ? 0 : this.getRucE().hashCode() );
         result = 37 * result + ( getCdDespacho() == null ? 0 : this.getCdDespacho().hashCode() );
         return result;
   }   


}


