package emch.modelo.entidades;
// Generated 30-abr-2013 18:02:46 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TEmpresa generated by hbm2java
 */
public class TEmpresa  implements java.io.Serializable {


     private String rucE;
     private TUbigeo TUbigeo;
     private String rsocial;
     private Date fechaIni;
     private String direccion;
     private String telef;
     private byte[] logo;
     private Set<TAccesoe> TAccesoes = new HashSet<TAccesoe>(0);
     private Set<TDespacho> TDespachos = new HashSet<TDespacho>(0);
     private Set<TCliente> TClientes = new HashSet<TCliente>(0);

    public TEmpresa() {
    }

	
    public TEmpresa(String rucE, TUbigeo TUbigeo, String rsocial, Date fechaIni, String direccion, String telef) {
        this.rucE = rucE;
        this.TUbigeo = TUbigeo;
        this.rsocial = rsocial;
        this.fechaIni = fechaIni;
        this.direccion = direccion;
        this.telef = telef;
    }
    public TEmpresa(String rucE, TUbigeo TUbigeo, String rsocial, Date fechaIni, String direccion, String telef, byte[] logo, Set<TAccesoe> TAccesoes, Set<TDespacho> TDespachos, Set<TCliente> TClientes) {
       this.rucE = rucE;
       this.TUbigeo = TUbigeo;
       this.rsocial = rsocial;
       this.fechaIni = fechaIni;
       this.direccion = direccion;
       this.telef = telef;
       this.logo = logo;
       this.TAccesoes = TAccesoes;
       this.TDespachos = TDespachos;
       this.TClientes = TClientes;
    }
   
    public String getRucE() {
        return this.rucE;
    }
    
    public void setRucE(String rucE) {
        this.rucE = rucE;
    }
    public TUbigeo getTUbigeo() {
        return this.TUbigeo;
    }
    
    public void setTUbigeo(TUbigeo TUbigeo) {
        this.TUbigeo = TUbigeo;
    }
    public String getRsocial() {
        return this.rsocial;
    }
    
    public void setRsocial(String rsocial) {
        this.rsocial = rsocial;
    }
    public Date getFechaIni() {
        return this.fechaIni;
    }
    
    public void setFechaIni(Date fechaIni) {
        this.fechaIni = fechaIni;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelef() {
        return this.telef;
    }
    
    public void setTelef(String telef) {
        this.telef = telef;
    }
    public byte[] getLogo() {
        return this.logo;
    }
    
    public void setLogo(byte[] logo) {
        this.logo = logo;
    }
    public Set<TAccesoe> getTAccesoes() {
        return this.TAccesoes;
    }
    
    public void setTAccesoes(Set<TAccesoe> TAccesoes) {
        this.TAccesoes = TAccesoes;
    }
    public Set<TDespacho> getTDespachos() {
        return this.TDespachos;
    }
    
    public void setTDespachos(Set<TDespacho> TDespachos) {
        this.TDespachos = TDespachos;
    }
    public Set<TCliente> getTClientes() {
        return this.TClientes;
    }
    
    public void setTClientes(Set<TCliente> TClientes) {
        this.TClientes = TClientes;
    }




}


