package emch.modelo.entidades;
// Generated May 23, 2013 7:57:08 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TEstadoliq generated by hbm2java
 */
public class TEstadoliq  implements java.io.Serializable {


     private String cdEstadoLiq;
     private String nombre;
     private Set<TEstadoxliquidacion> TEstadoxliquidacions = new HashSet<TEstadoxliquidacion>(0);

    public TEstadoliq() {
    }

	
    public TEstadoliq(String cdEstadoLiq, String nombre) {
        this.cdEstadoLiq = cdEstadoLiq;
        this.nombre = nombre;
    }
    public TEstadoliq(String cdEstadoLiq, String nombre, Set<TEstadoxliquidacion> TEstadoxliquidacions) {
       this.cdEstadoLiq = cdEstadoLiq;
       this.nombre = nombre;
       this.TEstadoxliquidacions = TEstadoxliquidacions;
    }
   
    public String getCdEstadoLiq() {
        return this.cdEstadoLiq;
    }
    
    public void setCdEstadoLiq(String cdEstadoLiq) {
        this.cdEstadoLiq = cdEstadoLiq;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<TEstadoxliquidacion> getTEstadoxliquidacions() {
        return this.TEstadoxliquidacions;
    }
    
    public void setTEstadoxliquidacions(Set<TEstadoxliquidacion> TEstadoxliquidacions) {
        this.TEstadoxliquidacions = TEstadoxliquidacions;
    }




}


