package emch.modelo.entidades;
// Generated 31-may-2013 22:17:08 by Hibernate Tools 3.2.1.GA



/**
 * TImgspesaje generated by hbm2java
 */
public class TImgspesaje  implements java.io.Serializable {


     private TImgspesajeId id;
     private TPesaje TPesaje;
     private String nombre;
     private String imgRuta;

    public TImgspesaje() {
    }

	
    public TImgspesaje(TImgspesajeId id, TPesaje TPesaje, String nombre) {
        this.id = id;
        this.TPesaje = TPesaje;
        this.nombre = nombre;
    }
    public TImgspesaje(TImgspesajeId id, TPesaje TPesaje, String nombre, String imgRuta) {
       this.id = id;
       this.TPesaje = TPesaje;
       this.nombre = nombre;
       this.imgRuta = imgRuta;
    }
   
    public TImgspesajeId getId() {
        return this.id;
    }
    
    public void setId(TImgspesajeId id) {
        this.id = id;
    }
    public TPesaje getTPesaje() {
        return this.TPesaje;
    }
    
    public void setTPesaje(TPesaje TPesaje) {
        this.TPesaje = TPesaje;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getImgRuta() {
        return this.imgRuta;
    }
    
    public void setImgRuta(String imgRuta) {
        this.imgRuta = imgRuta;
    }




}


