package emch.modelo.entidades;
// Generated 01/11/2013 08:35:39 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * TIncidencia generated by hbm2java
 */
public class TIncidencia  implements java.io.Serializable {


     private String cdInc;
     private TControlviaje TControlviaje;
     private Date fechaInc;
     private String zona;
     private String problema;
     private String horaProb;
     private String observaciones;
     private String soluc;

    public TIncidencia() {
    }

	
    public TIncidencia(String cdInc, TControlviaje TControlviaje, Date fechaInc, String zona, String problema, String horaProb) {
        this.cdInc = cdInc;
        this.TControlviaje = TControlviaje;
        this.fechaInc = fechaInc;
        this.zona = zona;
        this.problema = problema;
        this.horaProb = horaProb;
    }
    public TIncidencia(String cdInc, TControlviaje TControlviaje, Date fechaInc, String zona, String problema, String horaProb, String observaciones, String soluc) {
       this.cdInc = cdInc;
       this.TControlviaje = TControlviaje;
       this.fechaInc = fechaInc;
       this.zona = zona;
       this.problema = problema;
       this.horaProb = horaProb;
       this.observaciones = observaciones;
       this.soluc = soluc;
    }
   
    public String getCdInc() {
        return this.cdInc;
    }
    
    public void setCdInc(String cdInc) {
        this.cdInc = cdInc;
    }
    public TControlviaje getTControlviaje() {
        return this.TControlviaje;
    }
    
    public void setTControlviaje(TControlviaje TControlviaje) {
        this.TControlviaje = TControlviaje;
    }
    public Date getFechaInc() {
        return this.fechaInc;
    }
    
    public void setFechaInc(Date fechaInc) {
        this.fechaInc = fechaInc;
    }
    public String getZona() {
        return this.zona;
    }
    
    public void setZona(String zona) {
        this.zona = zona;
    }
    public String getProblema() {
        return this.problema;
    }
    
    public void setProblema(String problema) {
        this.problema = problema;
    }
    public String getHoraProb() {
        return this.horaProb;
    }
    
    public void setHoraProb(String horaProb) {
        this.horaProb = horaProb;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public String getSoluc() {
        return this.soluc;
    }
    
    public void setSoluc(String soluc) {
        this.soluc = soluc;
    }




}


