package emch.modelo.entidades;
// Generated 05-jun-2013 2:10:37 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TMarca generated by hbm2java
 */
public class TMarca  implements java.io.Serializable {


     private int idMarca;
     private String nombreMarca;
     private String descripcion;
     private Set<TCamion> TCamions = new HashSet<TCamion>(0);

    public TMarca() {
    }

	
    public TMarca(int idMarca, String nombreMarca) {
        this.idMarca = idMarca;
        this.nombreMarca = nombreMarca;
    }
    public TMarca(int idMarca, String nombreMarca, String descripcion, Set<TCamion> TCamions) {
       this.idMarca = idMarca;
       this.nombreMarca = nombreMarca;
       this.descripcion = descripcion;
       this.TCamions = TCamions;
    }
   
    public int getIdMarca() {
        return this.idMarca;
    }
    
    public void setIdMarca(int idMarca) {
        this.idMarca = idMarca;
    }
    public String getNombreMarca() {
        return this.nombreMarca;
    }
    
    public void setNombreMarca(String nombreMarca) {
        this.nombreMarca = nombreMarca;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<TCamion> getTCamions() {
        return this.TCamions;
    }
    
    public void setTCamions(Set<TCamion> TCamions) {
        this.TCamions = TCamions;
    }




}


