package emch.modelo.entidades;
// Generated 29-may-2013 1:03:45 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TTipotrabajador generated by hbm2java
 */
public class TTipotrabajador  implements java.io.Serializable {


     private String cdTipoTrabajador;
     private String nombre;
     private Set<TTrabajador> TTrabajadors = new HashSet<TTrabajador>(0);

    public TTipotrabajador() {
    }

	
    public TTipotrabajador(String cdTipoTrabajador, String nombre) {
        this.cdTipoTrabajador = cdTipoTrabajador;
        this.nombre = nombre;
    }
    public TTipotrabajador(String cdTipoTrabajador, String nombre, Set<TTrabajador> TTrabajadors) {
       this.cdTipoTrabajador = cdTipoTrabajador;
       this.nombre = nombre;
       this.TTrabajadors = TTrabajadors;
    }
   
    public String getCdTipoTrabajador() {
        return this.cdTipoTrabajador;
    }
    
    public void setCdTipoTrabajador(String cdTipoTrabajador) {
        this.cdTipoTrabajador = cdTipoTrabajador;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<TTrabajador> getTTrabajadors() {
        return this.TTrabajadors;
    }
    
    public void setTTrabajadors(Set<TTrabajador> TTrabajadors) {
        this.TTrabajadors = TTrabajadors;
    }




}


