package emch.modelo.entidades;
// Generated 01/11/2013 08:35:39 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TTrabajadorxcamion generated by hbm2java
 */
public class TTrabajadorxcamion  implements java.io.Serializable {


     private String cdAsigCamion;
     private TTurno TTurno;
     private TTrabajador TTrabajador;
     private TCamion TCamion;
     private Date fechaAsig;
     private boolean estado;
     private String observacion;
     private Set<TDespachodet> TDespachodets = new HashSet<TDespachodet>(0);

    public TTrabajadorxcamion() {
    }

	
    public TTrabajadorxcamion(String cdAsigCamion, TTurno TTurno, TTrabajador TTrabajador, TCamion TCamion, Date fechaAsig, boolean estado) {
        this.cdAsigCamion = cdAsigCamion;
        this.TTurno = TTurno;
        this.TTrabajador = TTrabajador;
        this.TCamion = TCamion;
        this.fechaAsig = fechaAsig;
        this.estado = estado;
    }
    public TTrabajadorxcamion(String cdAsigCamion, TTurno TTurno, TTrabajador TTrabajador, TCamion TCamion, Date fechaAsig, boolean estado, String observacion, Set<TDespachodet> TDespachodets) {
       this.cdAsigCamion = cdAsigCamion;
       this.TTurno = TTurno;
       this.TTrabajador = TTrabajador;
       this.TCamion = TCamion;
       this.fechaAsig = fechaAsig;
       this.estado = estado;
       this.observacion = observacion;
       this.TDespachodets = TDespachodets;
    }
   
    public String getCdAsigCamion() {
        return this.cdAsigCamion;
    }
    
    public void setCdAsigCamion(String cdAsigCamion) {
        this.cdAsigCamion = cdAsigCamion;
    }
    public TTurno getTTurno() {
        return this.TTurno;
    }
    
    public void setTTurno(TTurno TTurno) {
        this.TTurno = TTurno;
    }
    public TTrabajador getTTrabajador() {
        return this.TTrabajador;
    }
    
    public void setTTrabajador(TTrabajador TTrabajador) {
        this.TTrabajador = TTrabajador;
    }
    public TCamion getTCamion() {
        return this.TCamion;
    }
    
    public void setTCamion(TCamion TCamion) {
        this.TCamion = TCamion;
    }
    public Date getFechaAsig() {
        return this.fechaAsig;
    }
    
    public void setFechaAsig(Date fechaAsig) {
        this.fechaAsig = fechaAsig;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public Set<TDespachodet> getTDespachodets() {
        return this.TDespachodets;
    }
    
    public void setTDespachodets(Set<TDespachodet> TDespachodets) {
        this.TDespachodets = TDespachodets;
    }




}


